### ISSUE TITLE
ISSUE-201 トライジドリング撮影

### ISSUE THREAD

**Issue by seconoid** [seconoid/HEW_Zidolympic#6]
トライジドリングでアップロードされた写真をアップロードできるようにする。
画面の流れは、22. tryj.jsp => 25.upload => 26.upload_confilm.jsp => 27.upload_comp.jsp
とする。

**Comment by StreetWorly** [comment]
須藤がやっています。

**Comment by StreetWorly** [comment]
カメラ機能、アップロード機能が完成
